name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name:
        env:
          USER: ${{DOCKER_USER}}
          PWD: ${{DOCKER_PASSWORD}}
          run: |
            docker login -u $USER -p $PWD
      - name: Build the Docker image
           run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: docker push
           run: |
              docker push
      
      
